name: "Example"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup BEAM"
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.19.x'
          otp-version: '28.x'

      - name: "Cache Dependencies"
        uses: actions/cache@v4
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: "Run Tests"
        run: |
          mix deps.get
          mix test || true

  credo:
    name: "Credo"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup BEAM"
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.19.x'
          otp-version: '28.x'

      - name: "Cache Dependencies"
        uses: actions/cache@v4
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      
      - name: "Run Credo"
        run: |
          mix deps.get
          mix credo --format=oneline || true
